# Site settings
title: vp's café
owner: Vishnu Padmanabhan
email: vp@vishnupadmanabhan.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website where I chronicle my life events and put my personal thoughts as well.
disclaimer: >
  This website is a personal journal. All thoughts and opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vishnupadmanabhan.com" # the base hostname & protocol for your site
twitter_username: neoelemento
github_username:  neoelemento

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
    style: compressed
gems:
  - jemoji
  - jekyll-paginate

permalink: /:title/
future: true
paginate: 10