# Site
name: "vishnupadmanabhan.com"
title: "vp"
description: "Without wax!"
logo: 'assets/images/vpscafe.png'
favicon: 'assets/images/vpr-logo.png'
baseurl: 'https://vishnupadmanabhan.com'
google_analytics: 'UA-96046394-1'
disqus: 'neoelemento'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
email: vp@vishnupadmanabhan.com
podcast: 'https://writerandgeek.com'

# Authors
authors:
  vishnu:
    name: Vishnu
    display_name: Vishnu
    avatar: 'assets/images/vishnu-2.jpg'
    email: vp@vishnupadmanabhan.com
    web: https://vishnupadmanabhan.com
    twitter: https://twitter.com/neoelemento
    description: "Author of vp's cafe. Podcaster. Coffee lover who can talk astronomy"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
